# manifest/flannel-baseline/cross-node/ping-test.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cross-node-ping-test
spec:
  template:
    spec:
      nodeName: k3s-node2
      containers:
      - name: client
        image: praqma/network-multitool
        command: ["ping", "-c", "100", "10.42.2.11"]
      restartPolicy: Never
  backoffLimit: 1
