---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-probe
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-probe
  namespace: default
  labels:
    app: network-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-probe
  template:
    metadata:
      labels:
        app: network-probe
    spec:
      serviceAccountName: network-probe
      # Deploy on master node for consistent network path
      nodeSelector:
        kubernetes.io/hostname: kube-master
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: probe
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install --no-cache-dir prometheus-client && \
          python /app/network_probe.py
        env:
        - name: ROBOT_CONTROL_HOST
          value: "robot-control-svc.default.svc.cluster.local"
        - name: ROBOT_CONTROL_UDP_PORT
          value: "5201"
        - name: SAFETY_SCANNER_HOST
          value: "safety-scanner-svc.default.svc.cluster.local"
        - name: SAFETY_SCANNER_TCP_PORT
          value: "5202"
        - name: PROBE_INTERVAL
          value: "0.5"
        - name: METRICS_PORT
          value: "9090"
        volumeMounts:
        - name: probe-script
          mountPath: /app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # Need CAP_NET_RAW for ICMP ping
        securityContext:
          capabilities:
            add:
            - NET_RAW
      volumes:
      - name: probe-script
        configMap:
          name: network-probe-script

---
apiVersion: v1
kind: Service
metadata:
  name: network-probe-svc
  namespace: default
  labels:
    app: network-probe
spec:
  selector:
    app: network-probe
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP