apiVersion: batch/v1
kind: Job
metadata:
  name: same-node-ping-test
spec:
  template:
    spec:
      containers:
      - name: client
        image: praqma/network-multitool
        command: ["ping", "-c", "100", "10.42.2.11"]
      restartPolicy: Never
  backoffLimit: 1
